export const Handles = Object.freeze({
    Student: "Student",
    Faculty: "Faculty",
    Member: "Member",
    Learner: "Learner",
    Instructor: "Instructor",
    Mentor: "Mentor",
    Staff: "Staff",
    Alumni: "Alumni",
    ProspectiveStudent: "ProspectiveStudent",
    Guest: "Guest",
    Other: "Other",
    Administrator: "Administrator",
    Observer: "Observer",
    None: "None",
});
